version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    image: api-deployment-image
    container_name: api-container
    ports: 
      - "80:80"
    depends_on:
      - mongodb
    links:
      - mongodb
  
  mongodb:
    image: mongo:3.4
    container_name: api-db-container
    expose:
      - "27017"