version: '2'

services:
  base:
    build:
      context: .
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    image: user/api
    container_name: api_base
  api:
    extends: 
      service: base
    container_name: api_main
    ports:
      - "5000:5000"
    depends_on:
      - base
      - mongodb
    links:
      - mongodb
    command: flask run --host=0.0.0.0
  mongodb:
    image: mongo:3.4
    container_name: api_db
    ports: 
      - "27017:27017"