version: '2'

services:
  api:
    build:
      context: .
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    image: user/api
    container_name: api_main
    ports:
      - "5000:5000"
    volumes:
      - ./.data/:/var/lib/dbdiffer
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4
    container_name: api_db
    expose: 
      - "27017"