version: '3'
services:
  api:
    build:
      context: ./api
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    ports: 
      - "80:5000"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mongo:3.6
    restart: unless-stopped